# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ru:
  languageCode: ru-ru
  contentDir: content/ru
  menu:
    main:
      - name: Обо мне
        url: '#about'
        weight: 10
      - name: Посты
        url: '#posts'
        weight: 20
      - name: Проекты
        url: '#preojects'
        weight: 30
      - name: Меороприятия
        url: '#talks'
        weight: 40
      - name: Публикации
        url: '#publications'
        weight: 50
      - name: Связаться
        url: '#contact'
        weight: 60